apiVersion: v1
kind: Namespace
metadata:
  name: projet

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace : projet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: messagerie
        - name: MYSQL_USER
          value: username
        - name: MYSQL_PASSWORD
          value: password
        ports: 
          - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: projet
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer 

---

# PHP Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: projet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: web_app:v1
        ports:
        - containerPort: 80

---

# PHP Application Service
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
  namespace: projet
spec:
  ports:
  - port: 80
  selector:
    app: php-app
  type: LoadBalancer
