apiVersion: v1
kind: Namespace
metadata:
  name: projet

---

apiVersion: v1
kind: Namespace
metadata:
  name: projet

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: projet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: projet
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace : projet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: projet
        - name: MYSQL_USER
          value: username
        - name: MYSQL_PASSWORD
          value: password
        ports:
          - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: projet
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer 
